# Generated by Django 2.2.6 on 2019-11-02 15:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='creator',
            new_name='author',
        ),
        migrations.AddField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
