# Generated by Django 3.0.2 on 2020-01-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20200107_1726'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='/media/default_recipe_img_01.jpg', upload_to='media/%Y/%m/%d/'),
        ),
    ]
