# Generated by Django 3.0.2 on 2020-01-10 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20200110_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='/media/default_recipe_img_01.jpg', upload_to='media/'),
        ),
    ]
