# Generated by Django 3.0.2 on 2020-01-10 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20200110_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='images/default_recipe_img_01.jpg', upload_to='images/'),
        ),
    ]
