# Generated by Django 3.0.2 on 2020-01-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_auto_20200111_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='thumbnail',
            field=models.ImageField(default='thumbs/default_receipe_img_01_thumb.jpg', editable=False, upload_to='thumbs/'),
        ),
    ]
